name: 'L2-01'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-11/leaf@main
    - uses: stefanpenner/resolution-shard-13/leaf@main
    - uses: stefanpenner/resolution-shard-15/leaf@main
    - uses: stefanpenner/resolution-test/L3-01@main
