name: 'L2-02'
description: 'Layer 2 composite 02'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-03@main
      with:
        tag: 'L2-02 → leaf-03'
    - uses: stefanpenner/resolution-test/L3-03@main
    - uses: stefanpenner/resolution-test/L3-06@main
    - uses: stefanpenner/resolution-test/L3-10@main
