name: 'L1-04'
description: 'Layer 1 composite 04'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-05@main
      with:
        tag: 'L1-04 → leaf-05'
    - uses: stefanpenner/resolution-test/L2-05@main
    - uses: stefanpenner/resolution-test/L2-09@main
    - uses: stefanpenner/resolution-test/L2-02@main
