name: 'L1-04'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-9/leaf@main
    - uses: stefanpenner/resolution-shard-6/leaf@main
    - uses: stefanpenner/resolution-shard-8/leaf@main
    - uses: stefanpenner/resolution-test/L2-04@main
