name: 'L1-07'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-7/leaf@main
    - uses: stefanpenner/resolution-test/L2-07@main
    - uses: stefanpenner/resolution-test/L2-01@main
    - uses: stefanpenner/resolution-test/L2-05@main
