name: 'L1-03'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-8/leaf@main
    - uses: stefanpenner/resolution-shard-10/leaf@main
    - uses: stefanpenner/resolution-shard-7/leaf@main
    - uses: stefanpenner/resolution-test/L2-03@main
