name: 'L2-06'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-11/leaf@main
    - uses: stefanpenner/resolution-test/L3-06@main
    - uses: stefanpenner/resolution-test/L3-10@main
    - uses: stefanpenner/resolution-test/L3-04@main
