name: 'L3-05'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-20/leaf@main
    - uses: stefanpenner/resolution-shard-17/leaf@main
    - uses: stefanpenner/resolution-shard-19/leaf@main
    - uses: stefanpenner/resolution-test/L4-05@main
