name: 'L2-05'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-15/leaf@main
    - uses: stefanpenner/resolution-test/L3-05@main
    - uses: stefanpenner/resolution-test/L3-09@main
    - uses: stefanpenner/resolution-test/L3-03@main
