name: 'L4-08'
description: 'Layer 4 composite 08'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-09@main
      with:
        tag: 'L4-08 → leaf-09'
    - uses: stefanpenner/resolution-test/leaf-01@main
      with:
        tag: 'L4-08 → leaf-01'
    - uses: stefanpenner/resolution-test/leaf-04@main
      with:
        tag: 'L4-08 → leaf-04'
