name: 'L3-07'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-17/leaf@main
    - uses: stefanpenner/resolution-test/L4-07@main
    - uses: stefanpenner/resolution-test/L4-03@main
