name: 'L2-09'
description: 'Layer 2 composite 09'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-10@main
      with:
        tag: 'L2-09 → leaf-10'
    - uses: stefanpenner/resolution-test/L3-10@main
    - uses: stefanpenner/resolution-test/L3-03@main
    - uses: stefanpenner/resolution-test/L3-07@main
