name: 'L2-09'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-14/leaf@main
    - uses: stefanpenner/resolution-test/L3-09@main
    - uses: stefanpenner/resolution-test/L3-03@main
    - uses: stefanpenner/resolution-test/L3-07@main
