name: 'L2-08'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-13/leaf@main
    - uses: stefanpenner/resolution-test/L3-08@main
    - uses: stefanpenner/resolution-test/L3-02@main
    - uses: stefanpenner/resolution-test/L3-06@main
