name: 'L4-05'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-5/leaf@main
    - uses: stefanpenner/resolution-shard-3/leaf@main
    - uses: stefanpenner/resolution-shard-5/leaf@main
