name: 'L3-10'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-20/leaf@main
    - uses: stefanpenner/resolution-test/L4-10@main
    - uses: stefanpenner/resolution-test/L4-06@main
