name: 'L1-05'
description: 'Layer 1 composite 05'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-06@main
      with:
        tag: 'L1-05 → leaf-06'
    - uses: stefanpenner/resolution-test/L2-06@main
    - uses: stefanpenner/resolution-test/L2-10@main
    - uses: stefanpenner/resolution-test/L2-03@main
