name: 'L2-07'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-12/leaf@main
    - uses: stefanpenner/resolution-shard-14/leaf@main
    - uses: stefanpenner/resolution-shard-11/leaf@main
    - uses: stefanpenner/resolution-test/L3-07@main
