name: 'L3-01'
description: 'Layer 3 composite 01'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-02@main
      with:
        tag: 'L3-01 → leaf-02'
    - uses: stefanpenner/resolution-test/leaf-05@main
      with:
        tag: 'L3-01 → leaf-05'
    - uses: stefanpenner/resolution-test/L4-03@main
    - uses: stefanpenner/resolution-test/L4-08@main
