name: 'L3-01'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-16/leaf@main
    - uses: stefanpenner/resolution-test/L4-01@main
    - uses: stefanpenner/resolution-test/L4-07@main
