name: 'L3-02'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-17/leaf@main
    - uses: stefanpenner/resolution-shard-19/leaf@main
    - uses: stefanpenner/resolution-shard-16/leaf@main
    - uses: stefanpenner/resolution-test/L4-02@main
