name: 'L3-06'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-16/leaf@main
    - uses: stefanpenner/resolution-shard-18/leaf@main
    - uses: stefanpenner/resolution-shard-20/leaf@main
    - uses: stefanpenner/resolution-test/L4-06@main
