name: 'L1-06'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-6/leaf@main
    - uses: stefanpenner/resolution-test/L2-06@main
    - uses: stefanpenner/resolution-test/L2-10@main
    - uses: stefanpenner/resolution-test/L2-04@main
