name: 'L3-09'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-19/leaf@main
    - uses: stefanpenner/resolution-test/L4-09@main
    - uses: stefanpenner/resolution-test/L4-05@main
