name: 'Composite C'
description: 'Depth-1 composite'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-echo@main
      with:
        message: 'from composite-c (depth 1)'
    - uses: stefanpenner/resolution-test/composite-d@main
    - uses: stefanpenner/resolution-test/composite-e@main
