name: 'L4-04'
description: 'Layer 4 composite 04'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-test/leaf-05@main
      with:
        tag: 'L4-04 → leaf-05'
    - uses: stefanpenner/resolution-test/leaf-07@main
      with:
        tag: 'L4-04 → leaf-07'
    - uses: stefanpenner/resolution-test/leaf-10@main
      with:
        tag: 'L4-04 → leaf-10'
