name: 'L2-03'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-13/leaf@main
    - uses: stefanpenner/resolution-test/L3-03@main
    - uses: stefanpenner/resolution-test/L3-07@main
    - uses: stefanpenner/resolution-test/L3-01@main
