name: 'L2-03'
runs:
  using: 'composite'
  steps:
    - uses: stefanpenner/resolution-shard-13/leaf@main
    - uses: stefanpenner/resolution-shard-15/leaf@main
    - uses: stefanpenner/resolution-shard-12/leaf@main
    - uses: stefanpenner/resolution-test/L3-03@main
